package com.echo.junkman.smileface;

public enum ItemType {
	 TYPE_MONEY_100,
	 TYPE_MONEY_50,
	 TYPE_MONEY_20,
	 TYPE_MONEY_10,
	 TYPE_MONEY_5,
	 TYPE_MONEY_1,
	 TYPE_MONEY_COIN_1,
	 TYPE_MONEY_COIN_0_5,
	 TYPE_MONEY_COIN_0_1,
	 TYPE_MONEY_COIN_0_0_5,
	 TYPE_MONEY_COIN_0_0_2,
	 TYPE_MONEY_COIN_0_0_1,
	
	 TYPE_MONEY_FAKE_100,
	 TYPE_MONEY_FAKE_50,
	 TYPE_MONEY_FAKE_20,
	 TYPE_MONEY_FAKE_10,
	 TYPE_MONEY_FAKE_5,
	 TYPE_MONEY_FAKE_1,
	
	 TYPE_BOMB,
	 TYPE_PEACH,
	 TYPE_SHIT,
	 TYPE_BRICK,
	 TYPE_PAPER,
	 TYPE_LEAVE,
	 TYPE_BOTTLE,
	 TYPE_PHONE,
	 TYPE_PHONE_1,
	 TYPE_PHONE_2,
	 TYPE_PHONE_3,
	 TYPE_PHONE_4,
	 TYPE_CONDOM,
	 TYPE_PEARL,
	 
	 TYPE_UNKNOWN
}
